on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: mysmbtech.azurecr.io
        username: ${{ secrets.acr_mysmbtech_username }}
        password: ${{ secrets.acr_mysmbtech_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t mysmbtech.azurecr.io/akscluster:${{ github.sha }}
        docker push mysmbtech.azurecr.io/akscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_akscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep akscluster9a69 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace akscluster9a69`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: akscluster9a69
        container-registry-url: mysmbtech.azurecr.io
        container-registry-username: ${{ secrets.acr_mysmbtech_username }}
        container-registry-password: ${{ secrets.acr_mysmbtech_password }}
        secret-name: aksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: akscluster9a69
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          mysmbtech.azurecr.io/akscluster:${{ github.sha }}
        imagepullsecrets: |
          aksclusterdockerauth